### 获取验证码
POST http://47.119.178.225:8092/api/v1/user/captcha
Content-Type: application/json

{
  "token": "15282056609",
  "phoneNum": "15281991073"
}

### 登录验证
POST http://47.119.178.22:8092/api/v1/user/authenticate
Content-Type: application/json

{
  "username": "15281991073",
  "password": "429457"
}


### 登出
POST http://localhost:8092/api/v1/user/logout
Content-Type: application/json

{
  "id": "4c61b4fa-d393-4dc6-ab88-5175c72c4564",
  "username": "15281991073"
}


### 修改用户信息
POST http://brightminds.blue16.cn:8092/api/v1/user/updateInfo
Content-Type: application/json

{
  "token": "18192ada-9bc2-449f-b12f-03c610a13efb",
  "data":{
    "username": "15281991073",
    "name": "haha",
    "gender": "male",
    "age": "21",
    "hobby": "haha",
    "information": "123"
  }

}